// Generated by scripts/build-catalog.mjs.

export type ArticleType = "opiniao" | "noticia" | "cientifico";

export type Article = {
  id: string;
  title: string;
  author: string;
  source: string;
  publishedAt: string;
  type: ArticleType;
  theme: string;
  subtheme: string;
  tags: string[];
  summary: string;
  originalUrl: string;
  cover: string;
  pages: number;
  pdfReady: boolean;
};

export const articles: Article[] = [
  {
    "id": "10-great-free-ai-learning-resources-for-2026-by-omar-s-2114e37",
    "title": "10 Great Free AI Learning Resources for 2026",
    "author": "Omar Santos",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Aprendizado e Pesquisa",
    "tags": [
      "Aprendizado"
    ],
    "summary": "Leitura sobre aprendizado e pesquisa, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/45c7d6de6867",
    "cover": "/covers/10-great-free-ai-learning-resources-for-2026-by-omar-s-2114e37-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "20-hidden-notebooklm-features-most-users-never-discove-ab46df1",
    "title": "20 Hidden NotebookLM Features Most Users Never Discover",
    "author": "Mubashir Burfat",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Produtividade com IA e NotebookLM",
    "tags": [
      "NotebookLM"
    ],
    "summary": "Leitura sobre produtividade com ia e notebooklm, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/076ca3c1a31f",
    "cover": "/covers/20-hidden-notebooklm-features-most-users-never-discove-ab46df1-01.jpg",
    "pages": 19,
    "pdfReady": false
  },
  {
    "id": "6-research-papers-every-data-scientist-should-read-in--b756c4a",
    "title": "6 Research Papers Every Data Scientist Should Read In 2026",
    "author": "Andres Vourakis",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Aprendizado e Pesquisa",
    "tags": [
      "Pesquisa"
    ],
    "summary": "Leitura sobre aprendizado e pesquisa, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/eeb660fd2db1",
    "cover": "/covers/6-research-papers-every-data-scientist-should-read-in--b756c4a-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "7-genai-terms-that-keep-showing-up-everywhere-by-shrey-b83ea93",
    "title": "7 GenAI Terms That Keep Showing Up Everywhere",
    "author": "Shreyas Naphad",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Conceitos e Fundamentos",
    "tags": [
      "IA generativa"
    ],
    "summary": "Leitura sobre conceitos e fundamentos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/7e5d81f0639c",
    "cover": "/covers/7-genai-terms-that-keep-showing-up-everywhere-by-shrey-b83ea93-1.jpg",
    "pages": 9,
    "pdfReady": false
  },
  {
    "id": "7-super-dangerous-things-to-build-with-anthropic-s-fab-07a6546",
    "title": "7 Super Dangerous Things To Build With Anthropic’s Fable 5 Before It Gets Banned Again",
    "author": "Joe Procopio",
    "source": "Entrepreneurship Handbook",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Anthropic"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/85696b234e7a",
    "cover": "/covers/7-super-dangerous-things-to-build-with-anthropic-s-fab-07a6546-1.jpg",
    "pages": 7,
    "pdfReady": false
  },
  {
    "id": "agent-harnesses-with-claude-intuitively-and-exhaustive-12b1fb0",
    "title": "Agent Harnesses with Claude — Intuitively and Exhaustively Explained",
    "author": "Daniel Warfield",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Arquitetura de Agentes",
    "tags": [
      "Agentes",
      "Claude"
    ],
    "summary": "Leitura sobre arquitetura de agentes, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/1ab5a3697d5f",
    "cover": "/covers/agent-harnesses-with-claude-intuitively-and-exhaustive-12b1fb0-01.jpg",
    "pages": 53,
    "pdfReady": false
  },
  {
    "id": "ai-isn-t-magic-it-s-math-and-most-people-are-skipping--a681e9b",
    "title": "AI Isn’t Magic. It’s Math — and Most People Are Skipping the Hard Part",
    "author": "Robi Kumar Tomar",
    "source": "AI Mind",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Matematica para IA",
    "tags": [
      "Matemática"
    ],
    "summary": "Leitura sobre matematica para ia, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/571fd2c5c33f",
    "cover": "/covers/ai-isn-t-magic-it-s-math-and-most-people-are-skipping--a681e9b-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "anthropic-just-published-honest-data-nobody-in-ai-want-f12fb0b",
    "title": "Anthropic Just Published Honest Data Nobody in AI Wants to See",
    "author": "Marco Kotrotsos",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Anthropic"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/981f2591d0a9",
    "cover": "/covers/anthropic-just-published-honest-data-nobody-in-ai-want-f12fb0b-01.jpg",
    "pages": 11,
    "pdfReady": false
  },
  {
    "id": "attention-in-transformers-intuitively-explained-by-ama-17c4a19",
    "title": "Attention in Transformers — Intuitively Explained",
    "author": "Amarpreet Singh",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers",
      "Atenção"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/bd2f0f46d32a",
    "cover": "/covers/attention-in-transformers-intuitively-explained-by-ama-17c4a19-01.jpg",
    "pages": 23,
    "pdfReady": false
  },
  {
    "id": "attention-mechanism-the-brain-behind-llms-medium-739d813",
    "title": "Attention Mechanism: The Brain Behind LLMs",
    "author": "Autoria não identificada",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Atenção",
      "LLMs"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/67e2fdc84c5b",
    "cover": "/covers/attention-mechanism-the-brain-behind-llms-medium-739d813-01.jpg",
    "pages": 11,
    "pdfReady": false
  },
  {
    "id": "before-you-use-claude-cowork-build-this-first-by-the-p-531ea55",
    "title": "Before You Use Claude Cowork, Build This First",
    "author": "The PyCoach",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "MCP e Ferramentas Claude",
    "tags": [
      "MCP",
      "Claude"
    ],
    "summary": "Leitura sobre mcp e ferramentas claude, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/ce587b6bd41e",
    "cover": "/covers/before-you-use-claude-cowork-build-this-first-by-the-p-531ea55-01.jpg",
    "pages": 27,
    "pdfReady": false
  },
  {
    "id": "before-you-use-claude-create-this-file-by-the-pycoach--fb6cd6f",
    "title": "Before You Use Claude, Create This File",
    "author": "The PyCoach",
    "source": "Medium",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "MCP e Ferramentas Claude",
    "tags": [
      "MCP",
      "Claude"
    ],
    "summary": "Leitura sobre mcp e ferramentas claude, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/22049120b48a",
    "cover": "/covers/before-you-use-claude-create-this-file-by-the-pycoach--fb6cd6f-01.jpg",
    "pages": 16,
    "pdfReady": false
  },
  {
    "id": "chapter-3-what-is-a-transformer-by-generative-ai-mediu-a8b18e8",
    "title": "Chapter 3: What Is a Transformer",
    "author": "Generative AI",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/21a20c3fec2d",
    "cover": "/covers/chapter-3-what-is-a-transformer-by-generative-ai-mediu-a8b18e8-1.jpg",
    "pages": 7,
    "pdfReady": false
  },
  {
    "id": "chatgpt-is-getting-its-biggest-update-ever-by-tanmay-b-74727f4",
    "title": "ChatGPT Is Getting Its Biggest Update Ever",
    "author": "Tanmay Bansal",
    "source": "Artificial Intelligence in Plain English",
    "publishedAt": "Jun, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "ChatGPT"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/bacfef43d8ff",
    "cover": "/covers/chatgpt-is-getting-its-biggest-update-ever-by-tanmay-b-74727f4-1.jpg",
    "pages": 6,
    "pdfReady": false
  },
  {
    "id": "claude-code-agents-what-they-actually-are-data-science-283ad38",
    "title": "Claude Code agents: what they actually are",
    "author": "Autoria não identificada",
    "source": "Data Science Collective",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Arquitetura de Agentes",
    "tags": [
      "Agentes",
      "Claude"
    ],
    "summary": "Leitura sobre arquitetura de agentes, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/2d6ea121b936",
    "cover": "/covers/claude-code-agents-what-they-actually-are-data-science-283ad38-01.jpg",
    "pages": 19,
    "pdfReady": false
  },
  {
    "id": "claude-vs-gemini-which-ai-assistant-is-actually-more-u-29907f0",
    "title": "Claude vs. Gemini: Which AI Assistant Is Actually More Useful for Daily Work",
    "author": "Mubashir Burfat",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Claude",
      "Gemini"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/8d164d073955",
    "cover": "/covers/claude-vs-gemini-which-ai-assistant-is-actually-more-u-29907f0-1.jpg",
    "pages": 7,
    "pdfReady": false
  },
  {
    "id": "deepseek-just-did-what-the-industry-thought-was-imposs-2627cfe",
    "title": "DeepSeek Just Did What the Industry Thought Was Impossible",
    "author": "Pranit naik",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "DeepSeek",
      "Indústria"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/7321e7bb083d",
    "cover": "/covers/deepseek-just-did-what-the-industry-thought-was-imposs-2627cfe-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "did-anthropic-s-secret-model-mythos-6-just-leak-by-pra-1d8616b",
    "title": "Did Anthropic’s Secret Model, Mythos 6, Just Leak",
    "author": "Pranit naik",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Anthropic"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/5772a4a43ac7",
    "cover": "/covers/did-anthropic-s-secret-model-mythos-6-just-leak-by-pra-1d8616b-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "from-perceptron-to-transformers-understanding-how-ai-a-a7bc348",
    "title": "From Perceptron to Transformers. Understanding how AI actually learns.",
    "author": "@anello",
    "source": "Artificial Intelligence in Plain English",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Redes Neurais e Aprendizado",
    "tags": [
      "Transformers"
    ],
    "summary": "Leitura sobre redes neurais e aprendizado, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/a3af9fca6025",
    "cover": "/covers/from-perceptron-to-transformers-understanding-how-ai-a-a7bc348-01.jpg",
    "pages": 31,
    "pdfReady": false
  },
  {
    "id": "generative-ai-basic-concepts-llm-large-language-model--0812aad",
    "title": "Generative AI Basic Concepts. LLM (Large Language Model): The Large…",
    "author": "mustafabakla",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Conceitos e Fundamentos",
    "tags": [
      "LLMs",
      "IA generativa"
    ],
    "summary": "Leitura sobre conceitos e fundamentos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/8733a1ce1941",
    "cover": "/covers/generative-ai-basic-concepts-llm-large-language-model--0812aad-1.jpg",
    "pages": 5,
    "pdfReady": false
  },
  {
    "id": "glm-5-2-is-free-right-now-no-api-key-needed-and-it-sur-7d2910b",
    "title": "GLM-5.2 Is Free Right Now, No API Key Needed, and It Surprised Me",
    "author": "Nitin Gavhane",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/653632330ba9",
    "cover": "/covers/glm-5-2-is-free-right-now-no-api-key-needed-and-it-sur-7d2910b-1.jpg",
    "pages": 8,
    "pdfReady": false
  },
  {
    "id": "google-just-quietly-released-the-missing-piece-for-ai--48efda2",
    "title": "Google Just Quietly Released the Missing Piece for AI Agents. It’s Called OKF.",
    "author": "Akhil",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Bases vetoriais e conhecimento",
    "subtheme": "Formatos e Gestao do Conhecimento",
    "tags": [
      "Agentes"
    ],
    "summary": "Leitura sobre formatos e gestao do conhecimento, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/7e96a33898ce",
    "cover": "/covers/google-just-quietly-released-the-missing-piece-for-ai--48efda2-01.jpg",
    "pages": 14,
    "pdfReady": false
  },
  {
    "id": "gpt-5-6-beat-fable-5-which-frontier-model-should-you-a-c010bc5",
    "title": "GPT-5.6 Beat Fable 5. Which Frontier Model Should You Actually Use",
    "author": "Divy Yadav",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/9e3506b32441",
    "cover": "/covers/gpt-5-6-beat-fable-5-which-frontier-model-should-you-a-c010bc5-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "harness-engineering-explained-the-one-layer-behind-eve-95317cf",
    "title": "Harness Engineering Explained: The One Layer Behind Every AI Agent That Actually Works",
    "author": "Divy Yadav",
    "source": "Towards AI",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Arquitetura de Agentes",
    "tags": [
      "Agentes"
    ],
    "summary": "Leitura sobre arquitetura de agentes, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/471e82030049",
    "cover": "/covers/harness-engineering-explained-the-one-layer-behind-eve-95317cf-01.jpg",
    "pages": 17,
    "pdfReady": false
  },
  {
    "id": "how-deep-learning-actually-works-relu-backpropagation--21b6590",
    "title": "How Deep Learning Actually Works: ReLU, Backpropagation & Gradient Descent Explained Simply",
    "author": "Vikash Singh",
    "source": "Medium",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Redes Neurais e Aprendizado",
    "tags": [
      "Deep learning",
      "Gradiente",
      "Aprendizado"
    ],
    "summary": "Leitura sobre redes neurais e aprendizado, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/89f4fa5ee83e",
    "cover": "/covers/how-deep-learning-actually-works-relu-backpropagation--21b6590-01.jpg",
    "pages": 14,
    "pdfReady": false
  },
  {
    "id": "how-rnns-work-and-why-everyone-stopped-using-them-data-116f78a",
    "title": "How RNNs Work (And Why everyone Stopped Using Them)",
    "author": "Autoria não identificada",
    "source": "Data Science Collective",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "RNN"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/30d1986f5960",
    "cover": "/covers/how-rnns-work-and-why-everyone-stopped-using-them-data-116f78a-01.jpg",
    "pages": 22,
    "pdfReady": false
  },
  {
    "id": "how-to-build-real-leverage-when-everyone-has-ai-medium-1b53b76",
    "title": "How to Build Real Leverage When Everyone Has AI",
    "author": "Autoria não identificada",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Produtividade com IA e NotebookLM",
    "tags": [
      "RAG",
      "NotebookLM"
    ],
    "summary": "Leitura sobre produtividade com ia e notebooklm, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/bd487f400a0e",
    "cover": "/covers/how-to-build-real-leverage-when-everyone-has-ai-medium-1b53b76-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "how-to-use-ai-to-become-a-genius-i-know-this-seems-lik-dd6d2ed",
    "title": "How to use AI to become a genius. I know this seems like a very weird…",
    "author": "Mark Schaefer",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Produtividade com IA e NotebookLM",
    "tags": [
      "NotebookLM"
    ],
    "summary": "Leitura sobre produtividade com ia e notebooklm, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/d08ffab2f5d8",
    "cover": "/covers/how-to-use-ai-to-become-a-genius-i-know-this-seems-lik-dd6d2ed-01.jpg",
    "pages": 12,
    "pdfReady": false
  },
  {
    "id": "i-connected-these-7-mcps-to-claude-i-m-never-going-bac-40e8bbc",
    "title": "I Connected These 7 MCPs to Claude. I’m Never Going Back.",
    "author": "Mohd Anas",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "MCP e Ferramentas Claude",
    "tags": [
      "MCP",
      "Claude"
    ],
    "summary": "Leitura sobre mcp e ferramentas claude, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/b9f433b82a5b",
    "cover": "/covers/i-connected-these-7-mcps-to-claude-i-m-never-going-bac-40e8bbc-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "if-you-use-ai-in-2026-you-should-understand-these-17-c-06ddb75",
    "title": "If You Use AI in 2026, You Should Understand These 17 Concepts",
    "author": "Hamza Boulahia",
    "source": "Towards AI",
    "publishedAt": "Jul, 2026",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Conceitos e Fundamentos",
    "tags": [
      "LLMs e IA generativa"
    ],
    "summary": "Leitura sobre conceitos e fundamentos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/1b77515c55f5",
    "cover": "/covers/if-you-use-ai-in-2026-you-should-understand-these-17-c-06ddb75-01.jpg",
    "pages": 33,
    "pdfReady": false
  },
  {
    "id": "japan-just-beat-claude-mythos-and-nobody-saw-it-coming-50eead2",
    "title": "Japan Just Beat Claude Mythos And Nobody Saw It Coming",
    "author": "Pranit naik",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Claude"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/cc55238ec536",
    "cover": "/covers/japan-just-beat-claude-mythos-and-nobody-saw-it-coming-50eead2-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "linear-algebra-in-ai-vectors-matrices-and-self-attenti-dbc5a38",
    "title": "Linear Algebra in AI: Vectors, Matrices, and Self-Attention",
    "author": "The Dev Loop",
    "source": "Towards AI",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Matematica para IA",
    "tags": [
      "Matemática",
      "Álgebra linear",
      "Vetores",
      "Atenção"
    ],
    "summary": "Leitura sobre matematica para ia, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/955dc11703ba",
    "cover": "/covers/linear-algebra-in-ai-vectors-matrices-and-self-attenti-dbc5a38-01.jpg",
    "pages": 12,
    "pdfReady": false
  },
  {
    "id": "linear-algebra-you-ll-actually-use-part-1-by-anjali-ka-8800b3c",
    "title": "Linear Algebra You’ll Actually Use: Part 1",
    "author": "Anjali Kakde",
    "source": "Towards AI",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Matematica para IA",
    "tags": [
      "Matemática",
      "Álgebra linear"
    ],
    "summary": "Leitura sobre matematica para ia, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/4bbeb5ac06de",
    "cover": "/covers/linear-algebra-you-ll-actually-use-part-1-by-anjali-ka-8800b3c-01.jpg",
    "pages": 15,
    "pdfReady": false
  },
  {
    "id": "llms-still-don-t-understand-meaning-predict-13334c7",
    "title": "LLMs Still Don: t Understand Meaning",
    "author": "Autoria não identificada",
    "source": "Predict",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Modelos Limites e Impactos",
    "tags": [
      "LLMs"
    ],
    "summary": "Leitura sobre modelos limites e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/ffe7617861d6",
    "cover": "/covers/llms-still-don-t-understand-meaning-predict-13334c7-1.jpg",
    "pages": 9,
    "pdfReady": false
  },
  {
    "id": "llms-you-should-actually-learn-in-2026-by-shreyas-naph-87b5557",
    "title": "LLMs You Should Actually Learn in 2026",
    "author": "Shreyas Naphad",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Modelos Limites e Impactos",
    "tags": [
      "LLMs"
    ],
    "summary": "Leitura sobre modelos limites e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/e653d2d86ca9",
    "cover": "/covers/llms-you-should-actually-learn-in-2026-by-shreyas-naph-87b5557-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "llms-rag-agents-mcp-the-ai-evolution-you-must-know-a-v-be7d6a1",
    "title": "LLMs, RAG, Agents, MCP: The AI Evolution You Must Know (A Visual Explanation)",
    "author": "Divy Yadav",
    "source": "Towards AI",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Arquitetura de Agentes",
    "tags": [
      "LLMs",
      "Agentes",
      "RAG",
      "MCP"
    ],
    "summary": "Leitura sobre arquitetura de agentes, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/9ee07e421587",
    "cover": "/covers/llms-rag-agents-mcp-the-ai-evolution-you-must-know-a-v-be7d6a1-01.jpg",
    "pages": 19,
    "pdfReady": false
  },
  {
    "id": "machine-learning-for-complete-beginners-a-simple-30-da-f5eb264",
    "title": "Machine Learning for Complete Beginners: A Simple 30-Day Roadmap Without the Overwhelm",
    "author": "Harsh singh",
    "source": "Stackademic",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Aprendizado e Pesquisa",
    "tags": [
      "Aprendizado",
      "Roadmap"
    ],
    "summary": "Leitura sobre aprendizado e pesquisa, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/ca575929a7e3",
    "cover": "/covers/machine-learning-for-complete-beginners-a-simple-30-da-f5eb264-01.jpg",
    "pages": 15,
    "pdfReady": false
  },
  {
    "id": "neural-networks-as-simple-as-they-can-get-by-dr-ashish-31e80d9",
    "title": "Neural Networks, As Simple As They Can Get",
    "author": "Dr. Ashish Bamania",
    "source": "Level Up Coding",
    "publishedAt": "May, 2026",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Redes Neurais e Aprendizado",
    "tags": [
      "Redes neurais"
    ],
    "summary": "Leitura sobre redes neurais e aprendizado, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/f7e874e5cc54",
    "cover": "/covers/neural-networks-as-simple-as-they-can-get-by-dr-ashish-31e80d9-01.jpg",
    "pages": 15,
    "pdfReady": false
  },
  {
    "id": "notebooklm-s-new-feature-is-so-good-it-almost-feels-li-5cb051a",
    "title": "NotebookLM’s New Feature Is So Good It Almost Feels Like Cheating",
    "author": "Mubashir Burfat",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "opiniao",
    "theme": "Aprendizado, pesquisa e produtividade",
    "subtheme": "Produtividade com IA e NotebookLM",
    "tags": [
      "NotebookLM"
    ],
    "summary": "Leitura sobre produtividade com ia e notebooklm, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/f2d8f1567d1a",
    "cover": "/covers/notebooklm-s-new-feature-is-so-good-it-almost-feels-li-5cb051a-1.jpg",
    "pages": 9,
    "pdfReady": false
  },
  {
    "id": "open-knowledge-format-okf-why-google-thinks-ai-needs-a-4f5f0a1",
    "title": "Open Knowledge Format (OKF): Why Google Thinks AI Needs a Git for Knowledge",
    "author": "Arvind Kumar",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Bases vetoriais e conhecimento",
    "subtheme": "Formatos e Gestao do Conhecimento",
    "tags": [
      "Conhecimento"
    ],
    "summary": "Leitura sobre formatos e gestao do conhecimento, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/9dc9f08efb79",
    "cover": "/covers/open-knowledge-format-okf-why-google-thinks-ai-needs-a-4f5f0a1-01.jpg",
    "pages": 17,
    "pdfReady": false
  },
  {
    "id": "q-k-v-and-w-in-transformers-a-complete-step-by-step-nu-7a417a2",
    "title": "Q, K, V and W in Transformers — A Complete Step-by-Step Numeric Walkthrough",
    "author": "Dewasheesh Rana",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/3288b95827ae",
    "cover": "/covers/q-k-v-and-w-in-transformers-a-complete-step-by-step-nu-7a417a2-01.jpg",
    "pages": 20,
    "pdfReady": false
  },
  {
    "id": "stop-renting-ai-start-owning-it-by-andrew-zhu-jul-2026-340d7c2",
    "title": "Stop Renting AI — Start Owning It",
    "author": "Andrew Zhu",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/bbc80b13482e",
    "cover": "/covers/stop-renting-ai-start-owning-it-by-andrew-zhu-jul-2026-340d7c2-1.jpg",
    "pages": 8,
    "pdfReady": false
  },
  {
    "id": "surprise-ai-doesn-t-cause-layoffs-it-s-the-opposite-me-ef96be1",
    "title": "Surprise! AI Doesn’t Cause Layoffs. It’s the Opposite",
    "author": "Autoria não identificada",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/2b848309c080",
    "cover": "/covers/surprise-ai-doesn-t-cause-layoffs-it-s-the-opposite-me-ef96be1-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "the-ai-industry-as-you-know-it-died-today-by-alberto-r-c7630d7",
    "title": "The AI Industry as You Know It Died Today",
    "author": "Alberto Romero",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Indústria"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/59fce97a15c9",
    "cover": "/covers/the-ai-industry-as-you-know-it-died-today-by-alberto-r-c7630d7-1.jpg",
    "pages": 9,
    "pdfReady": false
  },
  {
    "id": "the-ai-industry-has-a-really-dark-secret-you-re-better-428b9f9",
    "title": "The AI Industry Has a Really Dark Secret You’re Better Off Not Knowing",
    "author": "Alberto Romero",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Indústria"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/9242a3576483",
    "cover": "/covers/the-ai-industry-has-a-really-dark-secret-you-re-better-428b9f9-01.jpg",
    "pages": 12,
    "pdfReady": false
  },
  {
    "id": "the-ai-race-is-over-no-one-new-can-catch-up-by-rekhi-j-1365670",
    "title": "The AI Race Is Over. No One New Can Catch Up.",
    "author": "Rekhi",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/7b6748ad6b72",
    "cover": "/covers/the-ai-race-is-over-no-one-new-can-catch-up-by-rekhi-j-1365670-1.jpg",
    "pages": 8,
    "pdfReady": false
  },
  {
    "id": "the-dangerous-myth-of-conscious-ai-chatbots-medium-f875a30",
    "title": "The Dangerous Myth of Conscious AI Chatbots",
    "author": "Autoria não identificada",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Modelos Limites e Impactos",
    "tags": [
      "LLMs e IA generativa"
    ],
    "summary": "Leitura sobre modelos limites e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/0f8d77f2667b",
    "cover": "/covers/the-dangerous-myth-of-conscious-ai-chatbots-medium-f875a30-01.jpg",
    "pages": 11,
    "pdfReady": false
  },
  {
    "id": "the-dark-side-of-ai-the-data-leak-problem-nobody-talks-48e59ec",
    "title": "The Dark Side of AI: The Data Leak Problem Nobody Talks About",
    "author": "Hayanan",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Engenharia e Seguranca de Apps",
    "tags": [
      "Privacidade"
    ],
    "summary": "Leitura sobre engenharia e seguranca de apps, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/4d7be42032fb",
    "cover": "/covers/the-dark-side-of-ai-the-data-leak-problem-nobody-talks-48e59ec-01.jpg",
    "pages": 22,
    "pdfReady": false
  },
  {
    "id": "the-death-of-consumer-ai-is-coming-by-will-lockett-jul-8205775",
    "title": "The Death Of Consumer AI Is Coming",
    "author": "Will Lockett",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/a9a5c24b8c23",
    "cover": "/covers/the-death-of-consumer-ai-is-coming-by-will-lockett-jul-8205775-1.jpg",
    "pages": 6,
    "pdfReady": false
  },
  {
    "id": "the-hidden-architecture-behind-most-llm-apps-by-shreya-1d6d542",
    "title": "The Hidden Architecture Behind Most LLM Apps",
    "author": "Shreyas Naphad",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Arquitetura de Agentes",
    "tags": [
      "LLMs",
      "Agentes"
    ],
    "summary": "Leitura sobre arquitetura de agentes, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/4caf2694d76e",
    "cover": "/covers/the-hidden-architecture-behind-most-llm-apps-by-shreya-1d6d542-01.jpg",
    "pages": 10,
    "pdfReady": false
  },
  {
    "id": "the-hidden-trick-that-makes-ai-apps-10x-faster-by-shre-c58d466",
    "title": "The Hidden Trick That Makes AI Apps 10x Faster",
    "author": "Shreyas Naphad",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Agentes, RAG e aplicações",
    "subtheme": "Engenharia e Seguranca de Apps",
    "tags": [
      "Agentes"
    ],
    "summary": "Leitura sobre engenharia e seguranca de apps, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/73e22554bac9",
    "cover": "/covers/the-hidden-trick-that-makes-ai-apps-10x-faster-by-shre-c58d466-01.jpg",
    "pages": 11,
    "pdfReady": false
  },
  {
    "id": "the-math-that-powers-modern-ai-the-small-set-of-formul-b0b11c7",
    "title": "The Math That Powers Modern AI. The Small Set of Formulas Behind Almost…",
    "author": "Gianpiero Andrenacci",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Matematica para IA",
    "tags": [
      "Matemática"
    ],
    "summary": "Leitura sobre matematica para ia, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/9ba654bfde1c",
    "cover": "/covers/the-math-that-powers-modern-ai-the-small-set-of-formul-b0b11c7-01.jpg",
    "pages": 38,
    "pdfReady": false
  },
  {
    "id": "the-mathematical-memory-of-ai-understanding-vector-dat-48bfcd1",
    "title": "The Mathematical Memory of AI: Understanding Vector Databases and Embedding Pipelines",
    "author": "Kuriko Iwai",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Bases vetoriais e conhecimento",
    "subtheme": "Vector Databases e Embeddings",
    "tags": [
      "Vetores",
      "Bases vetoriais",
      "Embeddings"
    ],
    "summary": "Leitura sobre vector databases e embeddings, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/85bd5fc13004",
    "cover": "/covers/the-mathematical-memory-of-ai-understanding-vector-dat-48bfcd1-01.jpg",
    "pages": 29,
    "pdfReady": false
  },
  {
    "id": "transformers-explained-why-attention-is-truly-all-you--6e2c778",
    "title": "Transformers Explained: Why Attention Is Truly All You Need",
    "author": "LM Po",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers",
      "Atenção"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/2e3669242965",
    "cover": "/covers/transformers-explained-why-attention-is-truly-all-you--6e2c778-01.jpg",
    "pages": 22,
    "pdfReady": false
  },
  {
    "id": "understanding-the-transformer-architecture-in-plain-en-40badba",
    "title": "Understanding the Transformer Architecture in Plain English",
    "author": "Md Johirul Islam",
    "source": "Artificial Intelligence in Plain English",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/24cd06724087",
    "cover": "/covers/understanding-the-transformer-architecture-in-plain-en-40badba-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "understanding-transformers-part-2-how-lstms-fixed-recu-fa6fd57",
    "title": "Understanding Transformers (Part 2): How LSTMs fixed Recurrent Networks (mostly)",
    "author": "Autoria não identificada",
    "source": "Data Science Collective",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers",
      "LSTM"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/dddb892471eb",
    "cover": "/covers/understanding-transformers-part-2-how-lstms-fixed-recu-fa6fd57-01.jpg",
    "pages": 22,
    "pdfReady": false
  },
  {
    "id": "understanding-transformers-part-3-positional-encodings-1d64398",
    "title": "Understanding Transformers (Part 3): Positional encodings and word embeddings",
    "author": "Autoria não identificada",
    "source": "Data Science Collective",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers",
      "Embeddings"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/3e3802f11a81",
    "cover": "/covers/understanding-transformers-part-3-positional-encodings-1d64398-01.jpg",
    "pages": 22,
    "pdfReady": false
  },
  {
    "id": "understanding-transformers-part-4-attention-is-just-a--ab0a6ee",
    "title": "Understanding Transformers (Part 4): Attention is just a few matrices",
    "author": "Autoria não identificada",
    "source": "Data Science Collective",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Transformers e atenção",
    "subtheme": "",
    "tags": [
      "Transformers",
      "Atenção"
    ],
    "summary": "Leitura sobre transformers e atenção, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/462505291833",
    "cover": "/covers/understanding-transformers-part-4-attention-is-just-a--ab0a6ee-01.jpg",
    "pages": 28,
    "pdfReady": false
  },
  {
    "id": "vector-databases-the-hidden-backbone-of-modern-ai-by-h-f141253",
    "title": "Vector Databases: The Hidden Backbone of Modern AI",
    "author": "Hemanth Raju Koneti",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Bases vetoriais e conhecimento",
    "subtheme": "Vector Databases e Embeddings",
    "tags": [
      "Vetores",
      "Bases vetoriais",
      "Embeddings"
    ],
    "summary": "Leitura sobre vector databases e embeddings, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/bdef4f6277a4",
    "cover": "/covers/vector-databases-the-hidden-backbone-of-modern-ai-by-h-f141253-01.jpg",
    "pages": 11,
    "pdfReady": false
  },
  {
    "id": "what-anthropic-didn-t-say-about-fable-5-s-return-by-ha-80b33a4",
    "title": "What Anthropic Didn’t Say About Fable 5’s Return",
    "author": "Han HELOIR YAN, Ph.D. ☕️",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Lancamentos e Comparativos de Modelos",
    "tags": [
      "Anthropic"
    ],
    "summary": "Leitura sobre lancamentos e comparativos de modelos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/2ebd29f8f2c4",
    "cover": "/covers/what-anthropic-didn-t-say-about-fable-5-s-return-by-ha-80b33a4-01.jpg",
    "pages": 17,
    "pdfReady": false
  },
  {
    "id": "what-is-an-llm-large-language-models-explained-2026-gu-0e69ff8",
    "title": "What Is an LLM: Large Language Models Explained (2026 Guide)",
    "author": "Shreyas Naphad",
    "source": "Medium",
    "publishedAt": "Jun, 2026",
    "type": "opiniao",
    "theme": "LLMs e IA generativa",
    "subtheme": "Conceitos e Fundamentos",
    "tags": [
      "LLMs"
    ],
    "summary": "Leitura sobre conceitos e fundamentos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/d926f473df2a",
    "cover": "/covers/what-is-an-llm-large-language-models-explained-2026-gu-0e69ff8-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "you-re-not-going-to-like-what-ai-becomes-after-july-12-e1a1924",
    "title": "You’re not going to like what AI becomes after July 12th.",
    "author": "Michal Malewicz",
    "source": "Medium",
    "publishedAt": "Jul, 2026",
    "type": "noticia",
    "theme": "Modelos, mercado e indústria",
    "subtheme": "Industria Estrategia e Impactos",
    "tags": [
      "Modelos"
    ],
    "summary": "Leitura sobre industria estrategia e impactos, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/b914e4d5edb6",
    "cover": "/covers/you-re-not-going-to-like-what-ai-becomes-after-july-12-e1a1924-01.jpg",
    "pages": 13,
    "pdfReady": false
  },
  {
    "id": "your-brain-already-understands-ai-here-s-how-neural-ne-0176a4c",
    "title": "Your Brain Already Understands AI. Here’s How Neural Networks Actually Work",
    "author": "CodeWithYog",
    "source": "Medium",
    "publishedAt": "Data não informada",
    "type": "opiniao",
    "theme": "Fundamentos, matemática e deep learning",
    "subtheme": "Redes Neurais e Aprendizado",
    "tags": [
      "Redes neurais"
    ],
    "summary": "Leitura sobre redes neurais e aprendizado, selecionada para o acervo de inteligência artificial.",
    "originalUrl": "https://medium.com/p/57e594c2a4c1",
    "cover": "/covers/your-brain-already-understands-ai-here-s-how-neural-ne-0176a4c-01.jpg",
    "pages": 15,
    "pdfReady": false
  }
];
