"use client";
import {useState} from "react";

const matrixNames=["Q","K","V","O","MLP 1","MLP 2"];
const explanations=[
  "Projeção que produz as consultas de todas as cabeças. Cada cabeça usa uma parte dessa projeção.",
  "Projeção que produz as chaves de todas as cabeças, comparadas com as consultas.",
  "Projeção que produz os valores: os conteúdos numéricos que a atenção combina.",
  "Recombina as saídas concatenadas das cabeças de atenção e retorna à dimensão do estado.",
  "Expande cada posição para 49.152 componentes, antes da ativação GELU.",
  "Retorna a 12.288 componentes, produzindo uma atualização que poderá ser somada ao estado.",
];
export function MatrixLandscape(){
  const [group,setGroup]=useState(1),[matrix,setMatrix]=useState(0);
  const dims=matrix===4?"49.152 × 12.288":matrix===5?"12.288 × 49.152":"12.288 × 12.288";
  return <div className="visual-card matrix-landscape"><p className="eyebrow">A PAISAGEM NUMÉRICA · GPT‑3 175B</p><h3>Uma frase entra. Seus estados atravessam a arquitetura.</h3><div className="landscape-input"><div><small>TEXTO</small><p>A vegetação saudável apresenta alta reflectância no infravermelho próximo.</p></div><i>→</i><div><small>TOKENS · ESQUEMA DIDÁTICO</small><p><b>A</b> <b>vegetação</b> <b>saudável</b> <span>…</span> <b>próximo</b></p></div><i>→</i><div><small>EMBEDDINGS</small><p>uma linha numérica copiada para cada token</p></div></div><div className="landscape-panorama"><svg viewBox="0 0 1080 570" role="img" aria-label="Panorama esquemático: matriz de embeddings seguida pelos blocos 1, 2, 3 e 96. Reticências representam os blocos intermediários. Cada grupo desenha quatro projeções de atenção e duas matrizes MLP."><defs><pattern id="matrix-grid" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M12 0H0V12" fill="none" stroke="#fff" strokeOpacity=".5" strokeWidth=".7"/></pattern></defs><path d="M70 475L990 215" stroke="#ced6e2" strokeWidth="45" strokeLinecap="round"/><path d="M70 475L240 427" stroke="#909dab" strokeWidth="7" strokeDasharray="6 6"/><path d="M240 427L465 363" stroke="#6754b8" strokeWidth="7" strokeDasharray="6 6"/><path d="M465 363L690 300" stroke="#267bc0" strokeWidth="7" strokeDasharray="6 6"/><path d="M690 300L990 215" stroke="#12847b" strokeWidth="7" strokeDasharray="6 6"/>
    <g transform="translate(48,255) skewY(-16)"><rect width="88" height="208" fill="#9a91b5" fillOpacity=".6" stroke="#6754b8" strokeWidth="2"/><rect width="88" height="208" fill="url(#matrix-grid)"/></g><text x="40" y="510" fontWeight="bold">Matriz de embeddings E</text><text x="40" y="533">50.257 × 12.288</text>
    {[{n:1,x:235,y:410},{n:2,x:440,y:350},{n:3,x:645,y:290},{n:96,x:880,y:225}].map(({n,x,y})=><g key={n}><g transform={`translate(${x},${y}) skewY(-16)`}>{[0,1,2,3,4,5].map((m)=><g key={m} transform={`translate(${m*15},${-m*6})`}><rect x="0" y={m===4?-146:-70} width={m===5?90:24} height={m===4?146:m===5?32:70} fill={m<4?"#267bc0":"#b74374"} fillOpacity={group===n?.5:.2} stroke={m<4?"#267bc0":"#b74374"} strokeWidth={group===n&&matrix===m?3:1}/><rect x="0" y={m===4?-146:-70} width={m===5?90:24} height={m===4?146:m===5?32:70} fill="url(#matrix-grid)"/></g>)}</g><text x={x+35} y={y+30} textAnchor="middle" fontWeight="bold">bloco {n}</text></g>)}<text x="810" y="300" fontSize="32">…</text><text x="740" y="400">os blocos 4 a 95 continuam a sequência</text><text x="60" y="48" fontWeight="bold">Os parâmetros ficam fixos.</text><text x="60" y="75">As representações temporárias seguem pela trilha.</text><text x="800" y="500" fontWeight="bold" fill="#12847b">→ normalização final</text><text x="800" y="524" fill="#12847b">→ escores → próximo token</text></svg></div><div className="landscape-legend"><span><i/>dicionário</span><span><i/>projeções da atenção</span><span><i/>matrizes da MLP</span><span>⋯ percurso dos estados</span></div><div className="landscape-inspector"><div><label>Qual grupo abrir?<select value={group} onChange={e=>setGroup(+e.target.value)}>{[1,2,3,96].map(n=><option key={n} value={n}>Bloco {n}</option>)}</select></label><div className="landscape-matrix-tabs">{matrixNames.map((n,i)=><button key={n} aria-pressed={matrix===i} onClick={()=>setMatrix(i)}>{n}</button>)}</div></div><div><span>MATRIZ {matrixNames[matrix]} · BLOCO {group}</span><h4>{dims}</h4><p>{explanations[matrix]}</p><small>Formato para vetores-coluna: linhas de saída × componentes de entrada. Outras convenções escrevem as matrizes transpostas, sem mudar a operação.</small></div></div><p className="diagram-caption">Figura original inspirada no ensaio <a href="https://www.ibm.com/think/news/what-does-ai-look-like" target="_blank" rel="noreferrer">“What does AI look like?”, da IBM</a>. O panorama é esquemático, sem escala geométrica. Na contagem simplificada do ensaio: 1 matriz de embeddings + 96 × 6 grandes matrizes = 577. Isso não enumera todos os arranjos de parâmetros: posições, vieses e normalizações também participam. As matrizes Q, K e V desenhadas agregam as projeções das 96 cabeças de um bloco.</p></div>;
}
